package edu.kit.outwait.customDataTypes

import org.joda.time.DateTime
import org.joda.time.Duration

/**
 * This class models a fixed slot, that means that the client, whose slot it is,
 * and the institution have arranged a fixed appointment time. Like all classes in
 * the customDataTypes it does not inherit from more general classes, so that it
 * can be serialized more easily. The main reason for this class is moving data
 * from one point to another. There are more advanced slot classes in the package waitingQueue
 *
 * @property duration how much time is scheduled for the slot.
 * @property slotCode the unique code, generated by the server, to identify the slot
 * @property appointmentTime originally arranged point in time of the appointment
 */
class FixedSlot(
    val duration: Duration,
    val slotCode: String,
    val appointmentTime: DateTime
)
