package edu.kit.outwait.customDataTypes

import org.joda.time.Duration
/**
 * This class models a spontaneous slot, that means that the client, whose slot it is,
 * and the institution had not arranged a fixed appointment time previously. Like all classes in
 * the customDataTypes it does not inherit from more general classes, so that it
 * can be serialized more easily. The main reason for this class is moving data
 * from one point to another. There are more advanced slot classes in the package waitingQueue
 *
 * @property duration how much time is scheduled for the slot.
 * @property slotCode the unique code, generated by the server, to identify the slot
 */
class SpontaneousSlot(
    val duration: Duration,
    val slotCode: String
)
