package edu.kit.outwait.waitingQueue.timeSlotModel

import org.joda.time.Interval

/**
 * This class represents a client time slot with its currently predicted time interval
 * additionally it contains the slot code for the client and the auxiliary identifier
 * that is given to him by the receptionist.
 *
 * @property slotCode the unique code, generated by the server, to identify the slot
 * @property auxiliaryIdentifier entered by the receptionist. helps to remember
 * the name of the client and/or details about the appointment
 * @constructor Creates ClientTimeSlot with given [slotCode], [auxiliaryIdentifier] and [interval]
 *
 * @param interval see [TimeSlot.interval]
 */
abstract class ClientTimeSlot(
    interval: Interval,
    val slotCode: String,
    val auxiliaryIdentifier: String
) : TimeSlot(interval)
