/* This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8/userguide/building_java_projects.html */
plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.20"

    id("tech.formatter-kt.formatter") version "0.7.2"

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    jacoco
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    //Use mavenCentral for JDBC
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("ch.qos.logback:logback-classic:1.2.1")

    implementation("org.json:json:20201115")

    implementation("com.corundumstudio.socketio:netty-socketio:1.7.18")

    implementation("com.sun.mail:jakarta.mail:2.0.0")
    implementation("jakarta.mail:jakarta.mail-api:2.0.0")

    // https://mvnrepository.com/artifact/mysql/mysql-connector-java
    implementation("mysql:mysql-connector-java:8.0.23")
    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
    implementation("org.junit.jupiter:junit-jupiter:5.4.2")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    //Mocking Library
    testImplementation("io.mockk:mockk:1.10.6")

    // Create a client mock
    testImplementation("io.socket:socket.io-client:1.0.0")

    // Mockk testing framework
    testImplementation("io.mockk:mockk:1.10.6")

    // Test coverage
    testImplementation("org.jacoco:org.jacoco.core:0.8.6")
}

tasks.test {
    useJUnitPlatform()

    testLogging {
        outputs.upToDateWhen { false }
        showStandardStreams = false // Enable this to see the logs in the tests
    }

    finalizedBy(tasks.jacocoTestReport) // report is always generated after tests run
}

tasks.jacocoTestReport {
    dependsOn(tasks.test) // tests are required to run before generating the report
}

jacoco {
    toolVersion = "0.8.6"
    reportsDirectory.set(file("$buildDir/coverage_report"))
}

application {
    // Define the main class for the application.
    mainClass.set("edu.kit.outwait.server.core.ServerKt")

    // Add dependencies
    tasks.withType<Jar>() {
        configurations["compileClasspath"]
            .forEach { file: File -> from(zipTree(file.absoluteFile)) }
        manifest { attributes(mapOf("Main-Class" to "edu.kit.outwait.server.core.ServerKt")) }
    }
}
