package edu.kit.outwait.instituteDatabase.rooms

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * This class helps room (through its annotations) to create a table
 * where every slot code has an auxiliary identifier.
 *
 * @property slotCode the unique code, generated by the server, to identify the slot
 * @property auxiliaryText entered by the receptionist. helps to remember
 * the name of the client and/or details about the appointment
 */
@Entity(tableName = "aux_identifiers")
data class DBAuxiliaryIdentifier (
        @PrimaryKey val slotCode : String,
        val auxiliaryText: String,
)
