package edu.kit.outwait.waitingQueue.gravityQueue

import edu.kit.outwait.waitingQueue.timeSlotModel.TimeSlot
import org.joda.time.Duration

/**
 * This class is models a client time slot with gravity characteristics (see [GravitySlot]).
 * Additionally to the [GravitySlot] properties it stores specific data related to
 * a client appointment
 *
 * @property slotCode the unique code, generated by the server, to identify the slot
 * @property auxiliaryIdentifier entered by the receptionist. helps to remember
 * the name of the client and/or details about the appointment
 * @constructor
 * Creates ClientGravitySlot with given [slotCode], [auxiliaryIdentifier] and [duration]
 *
 * @param duration see [GravitySlot.duration]
 */
abstract class ClientGravitySlot(
    val slotCode: String,
    duration: Duration,
    val auxiliaryIdentifier: String
) : GravitySlot(duration) {
    /**
     * Knowing the precedent time slot, the client gravity slot can convert itself into
     * the following client time slot, using its gravity characteristics.
     * @see GravitySlot.interval
     *
     * @param predecessor the already calculated, precedent time slot.
     * @return conversion into time slot as in method description
     */
    abstract fun toClientTimeSlot(predecessor: TimeSlot): TimeSlot
}
