package edu.kit.outwait.clientDatabase

import androidx.room.Entity
import androidx.room.PrimaryKey
import org.joda.time.DateTime
import org.joda.time.Duration

/**
 * This class bundles all information about a client slot which are important
 * for the client side of the app to work. While the [slotCode] is consistent
 * to identify the slot, all the other info can be resent by the server when it changes.
 *
 * @property slotCode the unique code, generated by the server, to identify the slot
 * @property institutionName name of the institution where the client is waiting with this slot
 * @property approximatedTime currently predicted starting time of the clients slot
 * @property originalAppointmentTime originally predicted starting time of the clients slot
 * @property notificationTime duration that has to be left before the client slot starts so
 * that the client gets notified
 * @property delayNotificationTime if the slot delays more than this duration,
 * the client gets notified.
 */
@Entity(tableName = "client_table")
data class ClientInfo (
    @PrimaryKey val slotCode : String,
    val institutionName: String,
    val approximatedTime: DateTime,
    val originalAppointmentTime: DateTime,
    val notificationTime: Duration,
    val delayNotificationTime: Duration
    )
